Rozne drobne
WarlockMud/mudlet-scripts pull request #26
Opened 2023-03-16 08:10 UTC by fiedya

- poprawki do boskich cech
- alias /team do zresetowania okna

2023-03-16 08:30 UTC, fiedya commented
Przesunelam wczesniej folder nizej w hierarchii, stad ta wielka zmiana w xaml. To nic nie zmienia

2023-03-16 16:40 UTC, ingwarsw commented on aliases/aliases.lua
> +end
dodala bys enter na koncu?

2023-03-16 16:42 UTC, ingwarsw requested changes
Zobacz 2 drobne zmiany w komentarzach..

2023-03-17 08:58 UTC, ingwarsw commented on aliases/aliases.lua
> +end
Nie na koncu funkcji dla graczy :) tylko na koncu pliku..
<img width="189" alt="image" src="https://user-images.githubusercontent.com/5390156/225858798-5054ff62-095c-48f9-b2ab-d30b893fed00.png">

2023-03-17 08:59 UTC, ingwarsw approved these changes

2023-03-17 09:00 UTC, merged